version: '3' 
 
volumes:
  media:
  pg_data_production: 
  static:
  static_frontend:

services: 
  db: 
    image: postgres:13.10 
    env_file: .env 
    volumes: 
      - pg_data_production:/var/lib/postgresql/data 
  backend: 
    image: gnyssyng/foodgram_backend 
    env_file: .env
    depends_on:
      - db
    volumes: 
      - static:/app/backend_static/
      - media:/app/media/
  frontend: 
    image: gnyssyng/foodgram_frontend 
    volumes: 
      - static_frontend:/static_frontend 
  infra: 
    image: gnyssyng/foodgram_gateway 
    env_file: .env 
    depends_on:
      - backend
      - db
    volumes: 
      - static:/backend_static/
      - media:/media/
      - static_frontend:/static_frontend
    ports: 
      - 9000:80 
