version: '3' 
 
volumes: 
  pg_data_production: 
  static:
  frontend_static:
  media:

services: 
  db: 
    image: postgres:13.10 
    env_file: .env 
    volumes: 
      - pg_data_production:/var/lib/postgresql/data 
  backend: 
    image: gnyssyng/foodgram_backend 
    env_file: .env
    depends_on:
      - db
    volumes: 
      - static:/backend_static
      - media:/app/media/
  frontend: 
    image: gnyssyng/foodgram_frontend 
    env_file: .env 
    command: cp -r /app/build/. /frontend_static/ 
    volumes: 
      - frontend_static:/frontend_static 
  infra: 
    image: gnyssyng/foodgram_gateway 
    env_file: .env 
    depends_on:
      - db
    volumes: 
      - static:/backend_static/
      - media:/media/
      - frontend_static:/frontend_static/
    ports: 
      - 9000:80 
