# Generated by Django 3.2.16 on 2024-03-29 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_recepie_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientinrecipe',
            name='recepie',
        ),
    ]
