# Generated by Django 3.2.16 on 2024-03-29 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_ingredientinrecipe_recepie'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientinrecipe',
            name='recepie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.recipe', verbose_name='Рецепт'),
            preserve_default=False,
        ),
    ]
