# Generated by Django 3.2.16 on 2024-03-29 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_ingredientinrecipe_recepie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientinrecipe',
            name='recepie',
        ),
    ]
