# Generated by Django 3.2.16 on 2024-03-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_ingredientinrecipe_recepie'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
