# Generated by Django 3.2.16 on 2024-03-29 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_recipe_cooking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientinrecipe',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.recipe', verbose_name='Рецпет'),
            preserve_default=False,
        ),
    ]
