# Generated by Django 3.2.16 on 2024-03-29 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_ingredientinrecipe_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientinrecipe',
            name='recipe',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ingredientinrecipe', verbose_name='Ингредиенты'),
        ),
    ]
