# Generated by Django 3.2.16 on 2024-03-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20240330_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientinrecipe',
            name='amount',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredients', through='api.IngredientInRecipe', to='api.Ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='api.Tag'),
        ),
    ]
