# Generated by Django 3.2.16 on 2024-03-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20240330_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientinrecipe',
            name='amount',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество'),
            preserve_default=False,
        ),
    ]
