# Generated by Django 3.2.16 on 2024-03-30 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0019_ingredientinrecipe_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourites',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_favourites', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='favourites',
            name='recepie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepies_favourites', to='api.recipe', verbose_name='Рецепт'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_cart', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('recepie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepies_cart', to='api.recipe', verbose_name='Рецепт')),
            ],
        ),
    ]
