# Generated by Django 3.2.16 on 2024-03-30 06:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0020_auto_20240330_0908'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favourites',
            new_name='Favorite',
        ),
    ]
