# Generated by Django 3.2.16 on 2024-03-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_favourites_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='recepie',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='recepie',
            new_name='recipe',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipe/images/'),
        ),
    ]
