# Generated by Django 3.2.16 on 2024-03-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20240330_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientinrecipe',
            name='amount',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество'),
            preserve_default=False,
        ),
    ]
